### ISSUE TITLE
Allow existing Batch account to be used for deployment

### ISSUE THREAD

**Issue by ascobie** [Azure/flamenco-manager-azure#13]
Customer quota is tied to their Batch account and creating a new Batch account every time means that customers start on default low quota. 

Please allow an existing Batch account to be used when deploying the Azure environment.

Thanks

**Comment by sybrenstuvel** [comment]
It can be, the batch account name can be specified on the commandline. Run the executable with the `-help` option to see the available options. Also, each re-run of the deployment application will use the same batch account.
